server:
  port: 8080

spring:
  application:
    name: management-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/management-db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcosplata98@gmail.com
    password: wyabnzhedqnyhytr
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  urlFront: http://localhost:4200/recover/

